branch-defaults:
  default:
    environment: Corosaveapp-env
environment-defaults:
  api-env:
    branch: null
    repository: null
global:
  application_name: corosaveapp
  default_ec2_keyname: null
  default_platform: python-3.7
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application